<?php
namespace GoBlocks\Blocks;

defined( 'ABSPATH' ) || exit;

use WP_Block;

/**
 * Container block — PHP render callback.
 *
 * A centered, width-constrained content wrapper. All styles (max-width, margins,
 * padding) are pre-generated by the TypeScript CssEngine and stored in
 * `attributes.generatedCss`. PHP only outputs the wrapper element.
 */
class Container extends BlockBase {

	public function get_name(): string {
		return 'container';
	}

	public function render( array $attributes, string $content, WP_Block $block ): string {
		$unique_id = $this->get_unique_id( $attributes );

		$tag_name    = $this->get_tag_name( $attributes, 'div' );
		$block_class = $this->get_block_class( $unique_id ); // gb-container-{uniqueId}
		$classes     = $this->build_class_string(
			$block_class,
			$this->get_global_classes( $attributes ),
			array( 'gb-container' )
		);
		$html_attrs  = $this->build_html_attrs( $this->get_html_attributes( $attributes ) );

		$aria_label = sanitize_text_field( (string) ( $attributes['ariaLabel'] ?? '' ) );
		if ( $aria_label ) {
			$html_attrs .= ' aria-label="' . esc_attr( $aria_label ) . '"';
		}

		return sprintf(
			'<%1$s class="%2$s"%3$s>%4$s</%1$s>',
			esc_attr( $tag_name ),
			$classes,
			$html_attrs,
			$content
		);
	}
}