<?php
namespace GoBlocks\Blocks;

defined( 'ABSPATH' ) || exit;

/**
 * Heading block — PHP render callback.
 *
 * Renders h1–h6 with optional anchor ID and optional link wrapping.
 * All scoped styles are pre-generated by the TypeScript CssEngine.
 */
class Heading extends BlockBase {

	/**
	 * Block slug (without namespace prefix).
	 *
	 * @return string
	 */
	public function get_name(): string {
		return 'heading';
	}

	/**
	 * Render the Heading block.
	 *
	 * @param array<string, mixed> $attributes Block attributes.
	 * @param string               $content    Inner blocks HTML (unused — Heading uses RichText).
	 * @param \WP_Block            $block      Block instance.
	 * @return string Rendered HTML.
	 */
	public function render( array $attributes, string $content, \WP_Block $block ): string {
		$unique_id = $this->get_unique_id( $attributes );

		$tag_name       = $this->get_tag_name( $attributes, 'h2' );
		$block_class    = $this->get_block_class( $unique_id );   // gb-heading-{uniqueId}
		$global_classes = $this->get_global_classes( $attributes );

		$extra_classes = array( 'gb-heading' );
		if ( ! empty( $attributes['textGradient'] ) ) {
			$extra_classes[] = 'gb-heading--gradient';
		}

		$classes  = $this->build_class_string( $block_class, $global_classes, $extra_classes );
		$html_attrs     = $this->build_html_attrs( $this->get_html_attributes( $attributes ) );

		// Anchor ID.
		$anchor = sanitize_key( (string) ( $attributes['anchor'] ?? '' ) );
		if ( $anchor ) {
			$html_attrs .= ' id="' . esc_attr( $anchor ) . '"';
		}

		// Rich text content — sanitize to allow standard inline HTML.
		$text_content = wp_kses_post( (string) ( $attributes['content'] ?? '' ) );

		if ( '' === $text_content ) {
			return '';
		}

		// Link wrapping: <hN><a href="...">content</a></hN>
		$link = esc_url( (string) ( $attributes['link'] ?? '' ) );
		if ( $link ) {
			$text_content = $this->wrap_with_link( $text_content, $link, $attributes );
		}

		return sprintf(
			'<%1$s class="%2$s"%3$s>%4$s</%1$s>',
			esc_attr( $tag_name ),
			$classes,       // already escaped by build_class_string
			$html_attrs,    // already escaped, has leading space when non-empty
			$text_content
		);
	}

	/**
	 * Wrap content in an <a> tag with safe href/target/rel.
	 *
	 * @param string               $text_content  Already-sanitized content HTML.
	 * @param string               $link          Already-escaped URL.
	 * @param array<string, mixed> $attributes    Block attributes.
	 * @return string
	 */
	private function wrap_with_link( string $text_content, string $link, array $attributes ): string {
		$target = (string) ( $attributes['linkTarget'] ?? '_self' );

		if ( ! in_array( $target, array( '_self', '_blank' ), true ) ) {
			$target = '_self';
		}

		$rel = sanitize_text_field( (string) ( $attributes['linkRel'] ?? '' ) );

		if ( '_blank' === $target ) {
			$rel_parts = array_unique(
				array_filter(
					array_merge( array( 'noopener', 'noreferrer' ), explode( ' ', $rel ) )
				)
			);
			$rel       = implode( ' ', $rel_parts );
		}

		$link_attrs  = ' href="' . $link . '"';
		$link_attrs .= ' target="' . esc_attr( $target ) . '"';

		if ( $rel ) {
			$link_attrs .= ' rel="' . esc_attr( $rel ) . '"';
		}

		return '<a' . $link_attrs . '>' . $text_content . '</a>';
	}
}
