<?php
namespace GoBlocks\Blocks;

defined( 'ABSPATH' ) || exit;

use WP_Block;

/**
 * Spacer block — PHP render callback.
 *
 * Outputs a fixed-height vertical spacer div. All visual styles are
 * pre-generated by the TypeScript CssEngine and stored in `attributes.generatedCss`.
 * PHP outputs the wrapper element with the correct classes.
 */
class Spacer extends BlockBase {

	/**
	 * Block name (without namespace prefix).
	 *
	 * @return string
	 */
	public function get_name(): string {
		return 'spacer';
	}

	/**
	 * Render the Spacer block.
	 *
	 * @param  array<string, mixed> $attributes Block attributes.
	 * @param  string               $content    Inner blocks HTML (unused).
	 * @param  WP_Block             $block      Block instance.
	 * @return string Rendered HTML.
	 */
	public function render( array $attributes, string $content, WP_Block $block ): string {
		$unique_id      = $this->get_unique_id( $attributes );
		$block_class    = $unique_id ? $this->get_block_class( $unique_id ) : '';
		$global_classes = $this->get_global_classes( $attributes );
		$classes        = $this->build_class_string(
			$block_class,
			$global_classes,
			array( 'gb-spacer' )
		);

		return sprintf(
			'<div class="%s" role="presentation" aria-hidden="true"></div>',
			$classes
		);
	}
}
