<?php
/**
 * Text.
 *
 * @package GoBlocks\Blocks
 */

namespace GoBlocks\Blocks;

defined( 'ABSPATH' ) || exit;

/**
 * Text block — PHP render callback.
 *
 * Renders rich text content stored in `attributes.content` inside the
 * appropriate HTML element. All scoped styles are pre-generated by the
 * TypeScript CssEngine and cached by CssEnqueue.
 */
class Text extends BlockBase {

	/**
	 * Block slug (without namespace prefix).
	 *
	 * @return string
	 */
	public function get_name(): string {
		return 'text';
	}

	/**
	 * Render the Text block.
	 *
	 * @param array<string, mixed> $attributes Block attributes.
	 * @param string               $content    Inner blocks HTML (unused — Text uses RichText).
	 * @param \WP_Block            $block      Block instance.
	 * @return string Rendered HTML.
	 */
	public function render( array $attributes, string $content, \WP_Block $block ): string {
		$unique_id = $this->get_unique_id( $attributes );

		$tag_name       = $this->get_tag_name( $attributes, 'p' );
		$block_class    = $this->get_block_class( $unique_id );   // gb-text-{uniqueId}.
		$global_classes = $this->get_global_classes( $attributes );

		$drop_cap = ! empty( $attributes['dropCap'] ) && true === $attributes['dropCap'];
		$extra    = array_values( array_filter( array( 'gb-text', $drop_cap ? 'gb-text--drop-cap' : '' ) ) );

		// build_class_string returns an already-escaped string.
		$classes    = $this->build_class_string( $block_class, $global_classes, $extra );
		$html_attrs = $this->build_html_attrs( $this->get_html_attributes( $attributes ) );

		// Rich text HTML is stored in the attribute; $content (inner blocks) is empty.
		$text_content = wp_kses_post( (string) ( $attributes['content'] ?? '' ) );

		if ( '' === $text_content ) {
			return '';
		}

		return sprintf(
			'<%1$s class="%2$s"%3$s>%4$s</%1$s>',
			esc_attr( $tag_name ),
			$classes,       // Already escaped by build_class_string.
			$html_attrs,    // Already escaped, has leading space when non-empty.
			$text_content
		);
	}
}
