<?php
/**
 * Title: Pricing — 3 Tier
 * Slug: goblocks/pricing-3tier
 * Description: Three pricing cards on a light background with a highlighted Pro tier in indigo gradient. Includes plan names, prices, feature lists, and action buttons.
 * Categories: goblocks
 * Keywords: pricing, plans, tiers, subscription, saas, cards
 * Viewport Width: 1280
 */
defined( 'ABSPATH' ) || exit;
?>
<!-- wp:goblocks/group {"uniqueId":"p6wrap","align":"full","tagName":"section","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-group-p6wrap{background:#f8fafc;padding:96px 48px;}.gb-group-p6feat1a,.gb-group-p6feat1b,.gb-group-p6feat1c,.gb-group-p6feat1d,.gb-group-p6feat3a,.gb-group-p6feat3b,.gb-group-p6feat3c,.gb-group-p6feat3d{display:flex;align-items:center;gap:10px;}.gb-group-p6feat2a,.gb-group-p6feat2b,.gb-group-p6feat2c,.gb-group-p6feat2d{display:flex;align-items:center;gap:10px;}.gb-group-p6check1,.gb-group-p6check2,.gb-group-p6check3{width:20px;height:20px;min-width:20px;background:#dcfce7;border-radius:50%;display:flex;align-items:center;justify-content:center;}.gb-group-p6check2b{width:20px;height:20px;min-width:20px;background:rgba(255,255,255,0.18);border-radius:50%;display:flex;align-items:center;justify-content:center;}@media(max-width:640px){.gb-group-p6wrap{padding:56px 20px;}}","blockVersion":1} -->

<!-- wp:goblocks/group {"uniqueId":"p6hdr","tagName":"div","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-group-p6hdr{text-align:center;max-width:600px;margin:0 auto 60px;}","blockVersion":1} -->
<!-- wp:goblocks/text {"uniqueId":"p6tag","content":"Pricing Plans","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6tag{display:inline-flex;background:#eff6ff;border:1px solid #c7d2fe;color:#4f46e5;font-size:11px;font-weight:700;padding:5px 14px;border-radius:999px;letter-spacing:0.07em;text-transform:uppercase;margin:0 0 16px;}","blockVersion":1} /-->
<!-- wp:goblocks/heading {"uniqueId":"p6h","content":"Simple, Transparent Pricing","tagName":"h2","level":2,"anchor":"","link":"","linkTarget":"_self","linkRel":"","ariaLabel":"","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-heading-p6h{font-size:clamp(1.85rem,3vw+0.5rem,2.75rem);font-weight:800;color:#0f172a;line-height:1.15;letter-spacing:-0.03em;margin:0 0 14px;}","blockVersion":1} /-->
<!-- wp:goblocks/text {"uniqueId":"p6sub","content":"Start free. Upgrade when you need more.","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6sub{font-size:1.05rem;color:#64748b;line-height:1.7;margin:0;}","blockVersion":1} /-->
<!-- /wp:goblocks/group -->

<!-- wp:goblocks/group {"uniqueId":"p6grid","tagName":"div","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-group-p6grid{display:grid;grid-template-columns:repeat(3,1fr);gap:24px;align-items:start;}@media(max-width:960px){.gb-group-p6grid{grid-template-columns:1fr;max-width:420px;margin:0 auto;}}","blockVersion":1} -->

<!-- wp:goblocks/group {"uniqueId":"p6c1","tagName":"div","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-group-p6c1{background:#fff;border:1px solid #e2e8f0;border-radius:20px;padding:36px;}@media(max-width:640px){.gb-group-p6c1{padding:28px 24px;}}","blockVersion":1} -->
<!-- wp:goblocks/text {"uniqueId":"p6n1","content":"Starter","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6n1{font-size:0.75rem;font-weight:800;color:#94a3b8;text-transform:uppercase;letter-spacing:0.1em;margin:0 0 14px;}","blockVersion":1} /-->
<!-- wp:goblocks/group {"uniqueId":"p6p1","tagName":"div","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-group-p6p1{display:flex;align-items:baseline;gap:4px;margin-bottom:6px;}","blockVersion":1} -->
<!-- wp:goblocks/heading {"uniqueId":"p6pr1","content":"$0","tagName":"h3","level":3,"anchor":"","link":"","linkTarget":"_self","linkRel":"","ariaLabel":"","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-heading-p6pr1{font-size:3rem;font-weight:900;color:#0f172a;margin:0;letter-spacing:-0.04em;line-height:1;}","blockVersion":1} /-->
<!-- /wp:goblocks/group -->
<!-- wp:goblocks/text {"uniqueId":"p6per1","content":"/month · Free forever","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6per1{font-size:0.9rem;color:#94a3b8;margin:0 0 28px;}","blockVersion":1} /-->
<!-- wp:goblocks/group {"uniqueId":"p6feats1","tagName":"div","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-group-p6feats1{display:flex;flex-direction:column;gap:12px;margin-bottom:32px;}","blockVersion":1} -->
<!-- wp:goblocks/text {"uniqueId":"p6f1a","content":"✓  Up to 5 pages","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6f1a{font-size:0.875rem;color:#374151;margin:0;}","blockVersion":1} /-->
<!-- wp:goblocks/text {"uniqueId":"p6f1b","content":"✓  12 core blocks","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6f1b{font-size:0.875rem;color:#374151;margin:0;}","blockVersion":1} /-->
<!-- wp:goblocks/text {"uniqueId":"p6f1c","content":"✓  Pattern library","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6f1c{font-size:0.875rem;color:#374151;margin:0;}","blockVersion":1} /-->
<!-- wp:goblocks/text {"uniqueId":"p6f1d","content":"✓  Community support","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6f1d{font-size:0.875rem;color:#374151;margin:0;}","blockVersion":1} /-->
<!-- /wp:goblocks/group -->
<!-- wp:goblocks/button {"uniqueId":"p6b1","text":"Get Started","href":"#","target":"_self","rel":"","download":false,"buttonType":"button","ariaLabel":"","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-button-p6b1{display:flex;align-items:center;justify-content:center;background:transparent;font-size:14px;font-weight:700;padding:14px 24px;border-radius:10px;text-decoration:none;border:2px solid #6366f1;transition:background 150ms;}.gb-button-p6b1:hover{background:#eff6ff;}.gb-button-p6b1 .gb-button__text{color:#4f46e5;}","blockVersion":1} /-->
<!-- /wp:goblocks/group -->

<!-- wp:goblocks/group {"uniqueId":"p6c2","tagName":"div","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-group-p6c2{background:linear-gradient(160deg,#3730a3,#4f46e5 40%,#7c3aed 100%);border-radius:20px;padding:40px;position:relative;box-shadow:0 16px 48px rgba(79,70,229,0.4),0 4px 12px rgba(0,0,0,0.15);transform:scale(1.04);}@media(max-width:960px){.gb-group-p6c2{transform:none;}}@media(max-width:640px){.gb-group-p6c2{padding:28px 24px;}}","blockVersion":1} -->
<!-- wp:goblocks/group {"uniqueId":"p6bdg","tagName":"div","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-group-p6bdg{display:inline-flex;background:rgba(255,255,255,0.18);backdrop-filter:blur(4px);border-radius:999px;padding:5px 14px;margin-bottom:22px;border:1px solid rgba(255,255,255,0.2);}","blockVersion":1} -->
<!-- wp:goblocks/text {"uniqueId":"p6bdgtxt","content":"Most Popular","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6bdgtxt{font-size:11px;font-weight:700;color:#fff;margin:0;letter-spacing:0.08em;text-transform:uppercase;}","blockVersion":1} /-->
<!-- /wp:goblocks/group -->
<!-- wp:goblocks/text {"uniqueId":"p6n2","content":"Pro","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6n2{font-size:0.75rem;font-weight:800;color:rgba(255,255,255,0.65);text-transform:uppercase;letter-spacing:0.1em;margin:0 0 14px;}","blockVersion":1} /-->
<!-- wp:goblocks/group {"uniqueId":"p6p2","tagName":"div","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-group-p6p2{display:flex;align-items:baseline;gap:4px;margin-bottom:6px;}","blockVersion":1} -->
<!-- wp:goblocks/heading {"uniqueId":"p6pr2","content":"$29","tagName":"h3","level":3,"anchor":"","link":"","linkTarget":"_self","linkRel":"","ariaLabel":"","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-heading-p6pr2{font-size:3rem;font-weight:900;color:#fff;margin:0;letter-spacing:-0.04em;line-height:1;}","blockVersion":1} /-->
<!-- /wp:goblocks/group -->
<!-- wp:goblocks/text {"uniqueId":"p6per2","content":"/month · billed annually","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6per2{font-size:0.9rem;color:rgba(255,255,255,0.65);margin:0 0 28px;}","blockVersion":1} /-->
<!-- wp:goblocks/group {"uniqueId":"p6feats2","tagName":"div","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-group-p6feats2{display:flex;flex-direction:column;gap:12px;margin-bottom:32px;}","blockVersion":1} -->
<!-- wp:goblocks/text {"uniqueId":"p6f2a","content":"✓  Unlimited pages","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6f2a{font-size:0.875rem;color:rgba(255,255,255,0.9);margin:0;}","blockVersion":1} /-->
<!-- wp:goblocks/text {"uniqueId":"p6f2b","content":"✓  All blocks + extensions","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6f2b{font-size:0.875rem;color:rgba(255,255,255,0.9);margin:0;}","blockVersion":1} /-->
<!-- wp:goblocks/text {"uniqueId":"p6f2c","content":"✓  Global Styles system","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6f2c{font-size:0.875rem;color:rgba(255,255,255,0.9);margin:0;}","blockVersion":1} /-->
<!-- wp:goblocks/text {"uniqueId":"p6f2d","content":"✓  Priority support","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6f2d{font-size:0.875rem;color:rgba(255,255,255,0.9);margin:0;}","blockVersion":1} /-->
<!-- /wp:goblocks/group -->
<!-- wp:goblocks/button {"uniqueId":"p6b2","text":"Start Free Trial","href":"#","target":"_self","rel":"","download":false,"buttonType":"button","ariaLabel":"","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-button-p6b2{display:flex;align-items:center;justify-content:center;background:#fff;font-size:14px;font-weight:700;padding:14px 24px;border-radius:10px;text-decoration:none;box-shadow:0 2px 12px rgba(0,0,0,0.18);transition:transform 150ms,box-shadow 150ms;}.gb-button-p6b2:hover{transform:translateY(-1px);box-shadow:0 4px 16px rgba(0,0,0,0.22);}.gb-button-p6b2 .gb-button__text{color:#4f46e5;}","blockVersion":1} /-->
<!-- /wp:goblocks/group -->

<!-- wp:goblocks/group {"uniqueId":"p6c3","tagName":"div","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-group-p6c3{background:#fff;border:1px solid #e2e8f0;border-radius:20px;padding:36px;}@media(max-width:640px){.gb-group-p6c3{padding:28px 24px;}}","blockVersion":1} -->
<!-- wp:goblocks/text {"uniqueId":"p6n3","content":"Agency","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6n3{font-size:0.75rem;font-weight:800;color:#94a3b8;text-transform:uppercase;letter-spacing:0.1em;margin:0 0 14px;}","blockVersion":1} /-->
<!-- wp:goblocks/group {"uniqueId":"p6p3","tagName":"div","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-group-p6p3{display:flex;align-items:baseline;gap:4px;margin-bottom:6px;}","blockVersion":1} -->
<!-- wp:goblocks/heading {"uniqueId":"p6pr3","content":"$99","tagName":"h3","level":3,"anchor":"","link":"","linkTarget":"_self","linkRel":"","ariaLabel":"","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-heading-p6pr3{font-size:3rem;font-weight:900;color:#0f172a;margin:0;letter-spacing:-0.04em;line-height:1;}","blockVersion":1} /-->
<!-- /wp:goblocks/group -->
<!-- wp:goblocks/text {"uniqueId":"p6per3","content":"/month · 25 client sites","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6per3{font-size:0.9rem;color:#94a3b8;margin:0 0 28px;}","blockVersion":1} /-->
<!-- wp:goblocks/group {"uniqueId":"p6feats3","tagName":"div","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-group-p6feats3{display:flex;flex-direction:column;gap:12px;margin-bottom:32px;}","blockVersion":1} -->
<!-- wp:goblocks/text {"uniqueId":"p6f3a","content":"✓  25 client sites","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6f3a{font-size:0.875rem;color:#374151;margin:0;}","blockVersion":1} /-->
<!-- wp:goblocks/text {"uniqueId":"p6f3b","content":"✓  White-label option","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6f3b{font-size:0.875rem;color:#374151;margin:0;}","blockVersion":1} /-->
<!-- wp:goblocks/text {"uniqueId":"p6f3c","content":"✓  REST API access","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6f3c{font-size:0.875rem;color:#374151;margin:0;}","blockVersion":1} /-->
<!-- wp:goblocks/text {"uniqueId":"p6f3d","content":"✓  Dedicated onboarding","tagName":"p","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-text-p6f3d{font-size:0.875rem;color:#374151;margin:0;}","blockVersion":1} /-->
<!-- /wp:goblocks/group -->
<!-- wp:goblocks/button {"uniqueId":"p6b3","text":"Contact Sales","href":"#","target":"_self","rel":"","download":false,"buttonType":"button","ariaLabel":"","styles":{},"globalClasses":[],"htmlAttributes":{},"dynamicContent":{},"generatedCss":".gb-button-p6b3{display:flex;align-items:center;justify-content:center;background:transparent;font-size:14px;font-weight:700;padding:14px 24px;border-radius:10px;text-decoration:none;border:2px solid #6366f1;transition:background 150ms;}.gb-button-p6b3:hover{background:#eff6ff;}.gb-button-p6b3 .gb-button__text{color:#4f46e5;}","blockVersion":1} /-->
<!-- /wp:goblocks/group -->

<!-- /wp:goblocks/group -->

<!-- /wp:goblocks/group -->
